CREATE TABLE JURUSAN (
ID PRIMARY KEY BIGINT,
NAMA_JURUSAN BIGINT);

CREATE TABLE DOSEN_WALI (
ID PRIMARY KEY BIGINT,
NRP BIGINT,
NAMA VARCHAR (255),
TANGGAL_LAHIR DATE,
ALAMAT VARCHAR (225),
NO_HP INT);

CREATE TABLE MAHASISWA (
ID PRIMARY KEY,
NPM INT,
NAMA VARCHAR(255),
TANGGAL_LAHIR DATE,
ALAMAT VARCHAR(225),
NO_HP INT,
JURUSAN_ID BIGINT,
FOREIGN KEY (ID) REFERENCES JURUSAN(ID),
DOSEN_WALI_ID BIGINT
FOREIGN KEY(ID) REFERENCES DOSEN_WALI(ID)
);

